### ISSUE TITLE
vc-ediff does not work for me

### ISSUE THREAD

**Issue by onaipevoli** [ryuslash/vc-p4#1]
Hi

Thank you for useful elisp.
Most vc-commands work for me but I have problem with vc-ediff command.
Original file is fetched with "text: " in each head of the lines thus all lines are marked as modified.
It's like below:

Current:
```
foo
bar
```

Original :
```
text: foo
text: bar
exit: 0
```

It seems that original file is fetched with P4 global option -s, (ie p4 -s print -q  file#n).

**Comment by ryuslash** [comment]
Thanks for reporting this! I've never used `vc-ediff` before,

That could very well be the case, I'll have a look to see what's going on there as soon as I can :)

**Comment by ryuslash** [comment]
I've pushed up a fix, please let me know if it works with the latest code :)

**Comment by onaipevoli** [comment]
Thank you very much for fixing!!
By personal reason it'll be take serveral days to get started the check. I'll get back to you after confirmation.

**Comment by onaipevoli** [comment]
I'm sorry for the very late response. I confirmed that it is working correctly now. Thank you!
